# Generated by Django 6.0.2 on 2026-02-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_phone',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='solved_tasks',
            field=models.IntegerField(default=0, verbose_name='Решено задач'),
        ),
    ]
