# Generated by Django 5.2.11 on 2026-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_remove_studentprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='solved_tasks_list',
            field=models.TextField(blank=True, default='[]', help_text='JSON-список ID решенных задач', verbose_name='Список решенных задач'),
        ),
    ]
