# Generated by Django 5.2.11 on 2026-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_studentprofile_solved_tasks_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='solved_tasks_list',
            field=models.TextField(blank=True, default='[]', help_text='JSON-список ID решенных задач (из UploadedProgram.task_id)', verbose_name='Список решенных задач'),
        ),
    ]
