# Generated by Django 6.0.2 on 2026-02-24 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('expert', 'Эксперт')], default='easy', max_length=20, unique=True, verbose_name='Уровень сложности')),
                ('display_name', models.CharField(max_length=50, verbose_name='Отображаемое название')),
                ('level_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('color_code', models.CharField(choices=[('success', 'Зеленый (Easy)'), ('warning', 'Желтый (Medium)'), ('danger', 'Красный (Hard)'), ('dark', 'Черный (Expert)')], default='secondary', max_length=20, verbose_name='Цвет для отображения')),
                ('description', models.TextField(blank=True, verbose_name='Описание уровня')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'ordering': ['level_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True)),
                ('test_file', models.FileField(help_text='Путь до папки задачи', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Всего попыток')),
                ('perfect_solutions', models.PositiveIntegerField(default=0, verbose_name='Успешных на 100% попыток')),
                ('last_attempt_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последняя попытка')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task_description_app.difficultylevel', verbose_name='Уровень сложности')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_file', models.FileField(upload_to='student_programs/%Y/%m/%d/')),
                ('program_path', models.CharField(blank=True, max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Загружено'), ('testing', 'Тестируется'), ('passed', 'Пройдено'), ('failed', 'Не пройдено')], default='uploaded', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='task_description_app.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
