# Generated by Django 6.0.2 on 2026-03-02 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_path', models.CharField(max_length=500, verbose_name='Путь к задаче')),
                ('task_id', models.CharField(max_length=50, verbose_name='ID задачи')),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время попытки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('correct', 'Верно'), ('incorrect', 'Неверно'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('code', models.TextField(blank=True, verbose_name='Код решения')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Решено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка решения',
                'verbose_name_plural': 'Попытки решения',
                'ordering': ['-attempt_time'],
            },
        ),
    ]
