# Generated by Django 5.2.11 on 2026-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0002_taskattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattempt',
            name='real_task_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID задачи'),
        ),
    ]
