# Generated by Django 5.2.11 on 2026-03-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0003_taskattempt_real_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='color_code',
            field=models.CharField(choices=[('success', 'Зеленый (Easy)'), ('warning', 'Желтый (Medium)'), ('danger', 'Красный (Hard)'), ('big_danger', 'Коричневый (Very_Hard)'), ('dark', 'Черный (Expert)')], default='secondary', max_length=20, verbose_name='Цвет для отображения'),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='level_name',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('very_hard', 'Очень_сложный'), ('expert', 'Эксперт')], default='easy', max_length=20, unique=True, verbose_name='Уровень сложности'),
        ),
    ]
