# Generated by Django 5.2.11 on 2026-03-17 04:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0005_alter_difficultylevel_color_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test_file',
        ),
        migrations.AddField(
            model_name='task',
            name='path',
            field=models.CharField(default=datetime.datetime(2026, 3, 17, 4, 54, 48, 483862, tzinfo=datetime.timezone.utc), max_length=500, verbose_name='Путь к task.md'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='test_files',
            field=models.JSONField(default=list, verbose_name='Файлы тестов'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='ClassStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень вложенности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='task_description_app.classstructure')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('max_score', models.IntegerField(default=10, verbose_name='Макс. балл')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_description_app.collection')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_description_app.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='tasks',
            field=models.ManyToManyField(through='task_description_app.CollectionItem', to='task_description_app.task'),
        ),
        migrations.CreateModel(
            name='TaskPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('structure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_placements', to='task_description_app.classstructure')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='task_description_app.task')),
            ],
            options={
                'ordering': ['structure_node__level', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='classstructure',
            index=models.Index(fields=['parent'], name='task_descri_parent__45c0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='classstructure',
            index=models.Index(fields=['level'], name='task_descri_level_69ad88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'task')},
        ),
        migrations.AddIndex(
            model_name='taskplacement',
            index=models.Index(fields=['structure_node'], name='task_descri_structu_b0e19e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskplacement',
            index=models.Index(fields=['task'], name='task_descri_task_id_4c1eaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskplacement',
            unique_together={('task', 'structure_node')},
        ),
    ]
