# Generated by Django 5.2.11 on 2026-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0006_remove_task_test_file_task_path_task_test_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstructure',
            options={'ordering': ['level', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='classstructure',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddIndex(
            model_name='classstructure',
            index=models.Index(fields=['order'], name='task_descri_order_a7997d_idx'),
        ),
    ]
