# Generated by Django 5.2.11 on 2026-03-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0007_alter_classstructure_options_classstructure_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичная'),
        ),
    ]
