# Generated by Django 5.2.11 on 2026-03-20 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0008_task_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подборка задач', 'verbose_name_plural': 'Подборки задач'},
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_type',
            field=models.CharField(choices=[('lesson', 'Урок'), ('test', 'Контрольная работа'), ('exam', 'Экзамен'), ('homework', 'Домашнее задание')], default='lesson', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='collection',
            name='show_results',
            field=models.BooleanField(default=True, verbose_name='Показывать результаты'),
        ),
        migrations.AddField(
            model_name='collection',
            name='target_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='collection',
            name='target_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='collection',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ограничение времени (мин)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательная'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичная'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tasks',
            field=models.ManyToManyField(related_name='collections', through='task_description_app.CollectionItem', to='task_description_app.task'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='task_description_app.collection'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='max_score',
            field=models.IntegerField(default=10, verbose_name='Максимальный балл'),
        ),
        migrations.CreateModel(
            name='CollectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('graded', 'Проверена')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('max_score', models.IntegerField(default=0, verbose_name='Максимум')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='task_description_app.collection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка выполнения',
                'verbose_name_plural': 'Попытки выполнения',
                'ordering': ['-started_at'],
            },
        ),
    ]
