# Generated by Django 6.0.2 on 2026-03-22 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0009_alter_collection_options_collection_collection_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('in_progress', 'Выполняется'), ('completed', 'Выполнено'), ('expired', 'Просрочено')], default='pending', max_length=20, verbose_name='Статус')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task_description_app.collection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('collection', 'student')},
            },
        ),
    ]
