# Generated by Django 5.2.11 on 2026-04-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0010_collectionassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='path',
        ),
        migrations.AlterField(
            model_name='taskattempt',
            name='task_id',
            field=models.CharField(max_length=50, verbose_name='ID задания'),
        ),
    ]
