# Generated by Django 5.2.11 on 2026-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0011_remove_task_path_alter_taskattempt_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='level_name',
            field=models.CharField(choices=[('A', 'Легкий'), ('B', 'Средний'), ('C', 'Сложный'), ('D', 'Очень сложный'), ('E', 'Эксперт')], default='easy', max_length=20, unique=True, verbose_name='Уровень сложности'),
        ),
    ]
