# Generated by Django 5.2.13 on 2026-05-02 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0012_alter_difficultylevel_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattempt',
            name='collection_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attempts', to='task_description_app.collectionattempt', verbose_name='Попытка контрольной работы'),
        ),
        migrations.AlterModelTable(
            name='classstructure',
            table='task_description_app_classstructure',
        ),
        migrations.AlterModelTable(
            name='collection',
            table='task_description_app_collection',
        ),
        migrations.AlterModelTable(
            name='collectionassignment',
            table='task_description_app_collectionassignment',
        ),
        migrations.AlterModelTable(
            name='collectionattempt',
            table='task_description_app_collectionattempt',
        ),
        migrations.AlterModelTable(
            name='collectionitem',
            table='task_description_app_collectionitem',
        ),
        migrations.AlterModelTable(
            name='difficultylevel',
            table='task_description_app_difficultylevel',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_description_app_task',
        ),
        migrations.AlterModelTable(
            name='taskattempt',
            table='task_description_app_taskattempt',
        ),
        migrations.AlterModelTable(
            name='taskplacement',
            table='task_description_app_taskplacement',
        ),
        migrations.AlterModelTable(
            name='uploadedprogram',
            table='task_description_app_uploadedprogram',
        ),
    ]
