# Generated by Django 5.2.13 on 2026-05-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0013_taskattempt_collection_attempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskattempt',
            old_name='collection_attempt',
            new_name='collection_attempt_id',
        ),
    ]
