# Generated by Django 5.2.13 on 2026-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0014_rename_collection_attempt_taskattempt_collection_attempt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='level_name',
            field=models.CharField(choices=[('A', "на оценку '3'"), ('B', "на оценку '4'"), ('C', "на оценку '5'"), ('D', "на две оценки '5'"), ('E', "на '5' в четверти")], default='easy', max_length=20, unique=True, verbose_name='Уровень сложности'),
        ),
    ]
