# Generated by Django 5.2.14 on 2026-05-19 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0015_alter_difficultylevel_level_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='автор задачи'),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='level_name',
            field=models.CharField(choices=[('A', 'Уровень A'), ('B', 'Уровень B'), ('C', 'Уровень C'), ('D', 'Уровень D'), ('E', 'Уровень E')], default='easy', max_length=20, unique=True, verbose_name='Уровень сложности'),
        ),
    ]
