# Generated by Django 5.2.14 on 2026-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_description_app', '0016_task_created_by_alter_difficultylevel_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplacement',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='Оригинальная привязка'),
        ),
    ]
