# Generated by Django 5.2.11 on 2026-02-12 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('md_file', models.FileField(help_text='Markdown файл с описанием задачи', upload_to='tasks/md/')),
                ('test_file', models.FileField(help_text='Python файл с тестами', upload_to='tasks/tests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_file', models.FileField(upload_to='student_programs/%Y/%m/%d/')),
                ('program_path', models.CharField(blank=True, max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Загружено'), ('testing', 'Тестируется'), ('passed', 'Пройдено'), ('failed', 'Не пройдено')], default='uploaded', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='temp_tests.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
