print("    _\|/_")
print("   O(@'@)O")
print("--ooO(_)Ooo--")
print("|  |  |  |  |")
print("|  |  |  |  |")
print("|  |  |  |  |")
print("|  |  |  |  |")
print("|  |  |  |  |")
print("|  |  |  |  |")
print("|  |  |  |  |")