# Generated by Django 5.2.11 on 2026-03-10 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 17, 58, 12, 173684), verbose_name='Создано'),
        ),
    ]
