# Generated by Django 6.0.2 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_solved', '✅ Задача решена'), ('task_attempt', '📝 Попытка решения'), ('student_registered', '👤 Новый ученик'), ('collection_assigned', '📚 Выдана контрольная работа'), ('collection_completed', '🎉 Контрольная выполнена'), ('system', '🔔 Системное')], default='task_solved', max_length=20, verbose_name='Тип'),
        ),
    ]
