# Generated by Django 5.2.11 on 2026-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_solved', '✅ Задача решена'), ('task_attempt', '📝 Попытка решения'), ('student_registered', '👤 Новый ученик'), ('collection_assigned', '📚 Выдана контрольная работа'), ('collection_completed', '🎉 Контрольная выполнена'), ('time_request', '⏰ Запрос на продление времени'), ('system', '🔔 Системное')], default='task_solved', max_length=20, verbose_name='Тип'),
        ),
    ]
